// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using habitapp.Data;

#nullable disable

namespace habitapp.Migrations
{
    [DbContext(typeof(HabitContext))]
    [Migration("20230724134933_AddStartDate")]
    partial class AddStartDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("habitapp.Models.Habit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Habit");
                });

            modelBuilder.Entity("habitapp.Models.HabitCompletion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedHabitid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("CompletedHabitid");

                    b.ToTable("HabitCompletions");
                });

            modelBuilder.Entity("habitapp.Models.HabitCompletion", b =>
                {
                    b.HasOne("habitapp.Models.Habit", "CompletedHabit")
                        .WithMany("CompletionHistory")
                        .HasForeignKey("CompletedHabitid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedHabit");
                });

            modelBuilder.Entity("habitapp.Models.Habit", b =>
                {
                    b.Navigation("CompletionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
